### ISSUE TITLE
Application loads incompletely on Safari and Chrome, but not in Chrome

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#71] opened 2020-05-05 18:10 UTC
I noticed that in my app (with Quasar components) some icons did not load when running in Safari.

I was able to replicate this behaviour with one of the example programs: https://justpy.io/quasar_tutorial/QExpansionItem/#example-2

The incomplete loading was present in Safari and Firefox, but not in Chrome. 

This is what I see:
![JustPy_and_JustPy_and_JustPy](https://user-images.githubusercontent.com/1711378/81100150-52d08c00-8f0c-11ea-91a4-ca0d2a82e4ef.png)

As soon as I click one of the buttons some (but not all) the icons/images are loaded.

**Comment by elimintz** [comment] 2020-05-05 18:42
Thanks for flagging this. I will look into it.

**Comment by AndreaPerna** [comment] 2020-05-05 19:29
I have the same problem also in Chrome

**Comment by knoxvilledatabase** [comment] 2020-05-05 20:55
I have the same issue when using the internet resources, its like something changed over the weekend. When I use the NO_INTERNET option, the problem goes away.

**Comment by elimintz** [comment] 2020-05-05 23:30
May 3 a new version of Quasar came out. That could be the problem. The NO_INTERNET option uses an older version. I suggest that as a workaround for now until I can figure out the problem. All this does is get the resources locally so you can use it when connected to the internet also.

Add the following line to justpy.env:
`NO_INTERNET = True`

**Comment by elimintz** [comment] 2020-05-06 00:04
It works is Quasar version 1.9.14 (which runs with the NO_INTERNET option) and not with the latest version 1.10.5 which loads via the CDN.  The new Quasar does not generate any errors so it is hard to know what is going on but I will keep digging.

In the meantime please use the NO_INTERNET option as specified above. Sorry for the inconvenience.

**Comment by elimintz** [comment] 2020-05-11 17:19
The issue is [solved](https://github.com/quasarframework/quasar/issues/7005) and the fix will be part of the next version.  

Many thanks to @pdanpdan and the Quasar team

**Closed by elimintz** 2020-05-11 17:19 UTC
